#pragma once

enum ETextureFlags : unsigned int
{
    TEXTURE_FLAG_NONE             = 0u,
    TEXTURE_FLAG_RENDER_TARGET    = BIT(1u),
    TEXTURE_FLAG_DEPTH_STENCIL    = BIT(2u),
    TEXTURE_FLAG_SHADER_RESOURCE  = BIT(3u),
    TEXTURE_FLAG_UNORDERED_ACCESS = BIT(4u),
    TEXTURE_FLAG_SWAP_CHAIN       = BIT(5u)
};

enum EPixelFormat
{
    PIXEL_FORMAT_UNKNOWN = 0,
    PIXEL_FORMAT_R8G8B8A8,
    PIXEL_FORMAT_R8G8B8A8_UINT,
    PIXEL_FORMAT_R10G10B10A2
};

enum EShaderStage
{
    SHADER_STAGE_VERTEX = 0,
    SHADER_STAGE_PIXEL,
    SHADER_STAGE_DOMAIN,
    SHADER_STAGE_HULL,
    SHADER_STAGE_GEOMETRY,
    SHADER_STAGE_COMPUTE
};

enum EPrimitiveTopology
{
    PRIMITIVE_TOPOLOGY_UNDEFINED                  = 0,
    PRIMITIVE_TOPOLOGY_POINTLIST                  = 1,
    PRIMITIVE_TOPOLOGY_LINELIST                   = 2,
    PRIMITIVE_TOPOLOGY_LINESTRIP                  = 3,
    PRIMITIVE_TOPOLOGY_TRIANGLELIST               = 4,
    PRIMITIVE_TOPOLOGY_TRIANGLESTRIP              = 5,
    PRIMITIVE_TOPOLOGY_LINELIST_ADJ               = 10,
    PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ              = 11,
    PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ           = 12,
    PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ          = 13,
    PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST  = 33,
    PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST  = 34,
    PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST  = 35,
    PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST  = 36,
    PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST  = 37,
    PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST  = 38,
    PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST  = 39,
    PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST  = 40,
    PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST  = 41,
    PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42,
    PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43,
    PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44,
    PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45,
    PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46,
    PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47,
    PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48,
    PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49,
    PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50,
    PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51,
    PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52,
    PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53,
    PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54,
    PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55,
    PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56,
    PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57,
    PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58,
    PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59,
    PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60,
    PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61,
    PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62,
    PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63,
    PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64,
};